### PR TITLE
FixedChest Command and some cleaning up

### PR DESCRIPTION
**Pull request by ov3rk1ll**
- Moved the cancelled member of all GameEvent subclasses into the superclass
- Removed the overwrite annotations in HungerGame because to were errors in java1.7 and not needed anyway
- Added the AddFixedChest command and registered the command in Defaults

### CODE REVIEW

**Comment by kitskub** [comment]
Can you put back the overwrite annotations? They're good because they allow me to confirm that if I change the interface, the implementation changes too.

**Comment by kitskub** [comment]
Btw, thanks :)

**Comment by ov3rk1ll** [comment]
I can add them back, but as I said, they cause compilor errors....

// Edit: for some reason eclipse did not save my project settings and kept building against 1.5. With 1.6+1.7 the errors are gone -_-

**Comment by kitskub** [comment]
Yeah, I compile to 1.6.

**Comment by kitskub** [comment]
Thank you!

**Pull request merged**
