### PR TITLE
Lightning, Grace message, EXP/Level reset

### PR DESCRIPTION
**Pull request by ov3rk1ll**
- Fix for http://dev.bukkit.org/server-mods/myhungergames/tickets/44-show-message-at-the-beginning-and-end-of-grace-period/
- Fix for http://dev.bukkit.org/server-mods/myhungergames/tickets/45-lightning-on-death-and-when-only-x-players-are-left/
- InventorySave will now save/reset level and exp

### CODE REVIEW

**Comment by kitskub** [comment]
Can you update the config.yml for the new nodes? Also, instead of making the lightning and graceperiod stuff in the same as the randomLocs, add it to a different runnable.

**Comment by kitskub** [comment]
I'm not sure I like having two different stats system. If you want to the new GameStats, could you remove the old one?

**Comment by ov3rk1ll** [comment]
I can remove the old one. I can have the same data (updateGames, updatePlayers) sent from the new one or we make one entirely different that works for "everyone"

**Comment by kitskub** [comment]
I'm not against combining them like you did. If the new one works (and has all the features of the old one) you can just delete the old one, and i'll update the web side

**Comment by ov3rk1ll** [comment]
It is missing the SQLStat getStat / requestPlayer code but I can just copy that over and keep it static. will do that a bit later then.

**Comment by ov3rk1ll** [comment]
StatHandler is not fully replaced.
However I did mess up my last commit a bit and now your last changes are in there as well....

**Comment by kitskub** [comment]
not? or now?

**Comment by ov3rk1ll** [comment]
... why the hell does my keyboard thinks i want to type not when i hit w?....
It should say "StatHandler is NOW fully replaced."

**Comment by kitskub** [comment]
I manually merged most of these changes. Except for the outside-game pvp setting.

**Comment by ov3rk1ll** [comment]
The pvp outside game function is something I need for my server. Since you can just disable it...why not...

If you have them all merged manually please close this pull request so i can fetch back from upstream.

**Comment by kitskub** [comment]
There are plenty of pvp disabling plugins out there. However, I don't want to clutter up the config.yml any more than it is. On that note. I'm going to close this, any more changes can be made in another PR

**Comment by kitskub** [comment]
http://dev.bukkit.org/server-mods/pvptoggle/

**Pull request closed without merging**
