### PR TITLE
New random chest algorithm

### PR DESCRIPTION
**Pull request by greatman**
Rewrote the chest algorithm. Looks working in my local tests.

Signed-off-by: William Lebel lebelwilliam@gmail.com

### CODE REVIEW

**Comment by kitskub** [comment]
Thank you!

**Comment by greatman** [comment]
No problem ;)

**Comment by kitskub** [comment]
What made you want to create a PR? I mean, how long have you been following development?

**Comment by greatman** [comment]
Gonna use it on my server :P

**Comment by kitskub** [comment]
Oh nice!

**Comment by kitskub** [comment]
I realized two problems with this:
1) It provides no variance of the number of items chest-to-chest
2) It doesn't account for the possible case where no items make it (Creating an IndexOOBException

I'm currently writing new code to fix this

**Comment by kitskub** [comment]
Also, the slots list is misused.

**Pull request merged**
